apiVersion: apps/v1
kind: Deployment
metadata:
  name: meme-app
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meme-app
  template:
    metadata:
      labels:
        app: meme-app
    spec:
      containers:
        - name: meme-app
          image: wededo4644/meme-gen:eae821a3f12d22584d341da756ac82a20c1a9c52
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
