apiVersion: apps/v1
kind: Deployment
metadata:
  name: meme-app
  namespace: argocd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meme-app
  template:
    metadata:
      labels:
        app: meme-app
    spec:
      containers:
        - name: meme-app
          image: wededo4644/meme-gen:4db8ae35803235c73326558f8f097a0a96645469
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
