apiVersion: apps/v1
kind: Deployment
metadata:
  name: meme-app
  namespace: argocd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meme-app
  template:
    metadata:
      labels:
        app: meme-app
    spec:
      containers:
        - name: meme-app
          image: wededo4644/meme-gen:74346a788be89961cdfdd66f060b50bb58d97146
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
