apiVersion: apps/v1
kind: Deployment
metadata:
  name: meme-app
  namespace: argocd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meme-app
  template:
    metadata:
      labels:
        app: meme-app
    spec:
      containers:
        - name: meme-app
          image: wededo4644/meme-gen:c9e28b2c537e4b94627abdca14070b51293dc4b4
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
