apiVersion: v1
kind: Service
metadata:
  name: meme-app
  namespace: argocd
spec:
  type: LoadBalancer
  selector:
    app: meme-app
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
      nodePort: 31000
